services:
  - type: web
    name: my-fastapi-backend
    env: python
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    buildCommand: |
      pip install -r requirements.txt
    startCommand: bash startup.sh
    plan: free
