services:
  - type: web
    name: my-fastapi-scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
