services:
  - type: web
    name: my-fastapi-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium

